// DO NOT EDIT!
// Code generated by ffjson <https://github.com/pquerna/ffjson>
// DO NOT EDIT!

package main

import (
	"github.com/pquerna/ffjson/inception"
	importedinceptionpackage "github.com/xidongc/qproxy/rpc"
)

func main() {
	i := ffjsoninception.NewInception("rpc/qproxy.pb.go", "rpc", "rpc/qproxy.pb_ffjson.go", false)
	i.AddMany(importedinceptionpackage.FFJSONExpose())
	i.Execute()
}
